import matplotlib.pyplot as plt


def show_params(Xref):
    """
    Plot the key features
    :param Xref:
    :return:
    """
    plt.figure()
    plt.subplot(3, 1, 1)
    plt.title("Volume")
    plt.plot(Xref.V.t, Xref.V.y)
    plt.xticks([])
    plt.subplot(3, 1, 2)
    plt.title("Penicillin Concentration")
    plt.plot(Xref.P.t, Xref.P.y)
    plt.xticks([])
    plt.subplot(3, 1, 3)
    plt.title("Discharge rate")
    plt.plot(Xref.Fremoved.t, Xref.Fremoved.y)
    plt.xticks([])

    plt.figure()
    plt.subplot(4, 4, 1)
    plt.title("Sugar feed rate")
    plt.plot(Xref.Fs.t, Xref.Fs.y)
    plt.xticks([])
    plt.subplot(4, 4, 2)
    plt.title("Soil bean feed rate")
    plt.plot(Xref.Foil.t, Xref.Foil.y)
    plt.xticks([])
    plt.subplot(4, 4, 3)
    plt.title("Aeration rate")
    plt.plot(Xref.Fg.t, Xref.Fg.y)
    plt.xticks([])
    plt.subplot(4, 4, 4)
    plt.title("Back pressure")
    plt.plot(Xref.pressure.t, Xref.pressure.y)
    plt.xticks([])
    plt.subplot(4, 4, 5)
    plt.title("Discharge rate")
    plt.plot(Xref.Fremoved.t, Xref.Fremoved.y)
    plt.xticks([])
    plt.subplot(4, 4, 6)
    plt.title("Water injection/dilution")
    plt.plot(Xref.Fw.t, Xref.Fw.y)
    plt.xticks([])
    plt.subplot(4, 4, 7)
    plt.title("Phenylacetic acid flowrate")
    plt.plot(Xref.Fpaa.t, Xref.Fpaa.y)
    plt.xticks([])
    plt.subplot(4, 4, 8)
    plt.title("pH")
    plt.plot(Xref.pH.t, Xref.pH.y, 'r')
    plt.xticks([])
    plt.subplot(4, 4, 9)
    plt.title("Temperature")
    plt.plot(Xref.T.t, Xref.T.y, 'r')
    plt.xticks([])
    plt.subplot(4, 4, 10)
    plt.title("Acid flowrate")
    plt.plot(Xref.Fa.t, Xref.Fa.y)
    plt.xticks([])
    plt.subplot(4, 4, 11)
    plt.title("Base flowrate")
    plt.plot(Xref.Fb.t, Xref.Fb.y)
    plt.xticks([])
    plt.subplot(4, 4, 12)
    plt.title("Cooling water")
    plt.plot(Xref.Fc.t, Xref.Fc.y)
    plt.xticks([])
    plt.subplot(4, 4, 13)
    plt.title("Heating water")
    plt.plot(Xref.Fh.t, Xref.Fh.y)
    plt.xticks([])
    plt.subplot(4, 4, 14)
    plt.title("Raman Spectra")
    plt.plot(Xref.Raman_Spec.Wavelength, Xref.Raman_Spec.Intensity)
    plt.xticks([])

    # plt.figure()
    # plt.title("Sequential batch control")
    # plt.plot(Xref.Fs.t, Xref.Fs.y, label='Sugar feed rate')
    # plt.plot(Xref.Fg.t, Xref.Fg.y, label='Aeration rate')
    # plt.plot(Xref.Fw.t, Xref.Fw.y, label='Water injection/dilution')
    # plt.plot(Xref.Fpaa.t, Xref.Fpaa.y, label='Phenylacetic acid flowrate')
    # plt.plot(Xref.RPM.t, Xref.RPM.y, label='Agitation RPM')
    # plt.plot(Xref.NH3_shots.t, Xref.NH3_shots.y, label='Nitrogen')
    # plt.legend()
    #
    # plt.figure()
    # plt.title("Sequential batch control")
    # plt.plot(Xref.Fremoved.t, Xref.Fremoved.y, label='Discharge rate')
    # plt.legend()
    #
    # plt.figure()
    # plt.subplot(2, 2, 1)
    # plt.title("PID Acid flowrate")
    # plt.plot(Xref.Fa.t, Xref.Fa.y, 'r')
    # plt.subplot(2, 2, 2)
    # plt.title("PID Base flowrate")
    # plt.plot(Xref.Fb.t, Xref.Fb.y, 'b')
    # plt.subplot(2, 2, 3)
    # plt.title("PID Cooling water")
    # plt.plot(Xref.Fc.t, Xref.Fc.y, 'g')
    # plt.subplot(2, 2, 4)
    # plt.title("PID Heating water")
    # plt.plot(Xref.Fh.t, Xref.Fh.y, 'y')
    #
    # plt.figure()
    # plt.subplot(2, 1, 1)
    # plt.title("pH")
    # plt.plot(Xref.pH.t, Xref.pH.y, 'r')
    # plt.subplot(2, 1, 2)
    # plt.title("Temperature")
    # plt.plot(Xref.T.t, Xref.T.y, 'b')

    plt.show()
