class X:
    """
    Batch data.
    """

    def __init__(self):
        self.Fg = ''
        self.RPM = ''
        self.Fs = ''
        self.sc = ''
        self.abc = ''
        self.Fa = ''
        self.Fb = ''
        self.Fc = ''
        self.Fh = ''
        self.Fw = ''
        self.pressure = ''
        self.Fremoved = ''
        self.S = ''
        self.DO2 = ''
        self.X = ''
        self.P = ''
        self.V = ''
        self.Wt = ''
        self.pH = ''
        self.T = ''
        self.Q = ''
        self.a0 = ''
        self.a1 = ''
        self.a3 = ''
        self.a4 = ''
        self.n0 = ''
        self.n1 = ''
        self.n2 = ''
        self.n3 = ''
        self.n4 = ''
        self.n5 = ''
        self.n6 = ''
        self.n7 = ''
        self.n8 = ''
        self.n9 = ''
        self.nm = ''
        self.phi0 = ''
        self.CO2outgas = ''
        self.Culture_age = ''
        self.Fpaa = ''
        self.PAA = ''
        self.PAA_offline = ''
        self.NH3 = ''
        self.NH3_offline = ''
        self.OUR = ''
        self.O2 = ''
        self.mup = ''
        self.mux = ''
        self.P_offline = ''
        self.X_CER = ''
        self.X_offline = ''
        self.CER = ''
        self.mu_X_calc = ''
        self.mu_P_calc = ''
        self.F_discharge_cal = ''
        self.NH3_shots = ''
        self.CO2_d = ''
        self.Viscosity = ''
        self.Viscosity_offline = ''
        self.Fault_ref = ''
        self.Control_ref = ''
        self.PAT_ref = ''
        self.Batch_ref = ''
        # extra
        self.PRBS_noise_addition = [0] * 1750
